#!/usr/bin/env python3
"""Generate the free-set summary table in layer_freeing_RESULTS.md from the artifacts.

    summary_table.py            # print it
    summary_table.py --write    # splice it into the doc between the markers

The doc carries `<!-- SUMMARY:BEGIN -->` / `<!-- SUMMARY:END -->` and everything between them is
regenerated; editing inside the markers by hand is pointless, the next run overwrites it.

This exists because the table it replaces was hand-written, and a hand-written copy of numbers is
the defect this program has found more often than any other: `04-coverage.md` drifted twice,
`consolidate.py` carried a hardcoded cell list and a hardcoded per-cell note, and the coverage table
in the sibling repository had to be generated for the same reason. Every column here is read from
the per-cell JSON the trainer wrote or from the downstream CSV the scorer wrote, so a new cell
appears the moment it exists and nobody has to remember to add it.

BPB and recovery come from `ple_<tag>.json`; mean accuracy is averaged over the ten `acc` rows of
`layer_freeing_downstream.csv`. Cells with no downstream row show `--` rather than a blank, so an
unscored cell is visibly unscored instead of looking like a missing value.
"""
import csv
import glob
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from olmoe_paths import DATA_DIR                              # noqa: E402
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from paths import ABLATIONS                                   # noqa: E402

BASE, IMPOSE = 0.6727, 2.7507
DOC = os.path.join(ABLATIONS, "layer_freeing_RESULTS.md")
DS = os.path.join(ABLATIONS, "layer_freeing_downstream.csv")
BEGIN, END = "<!-- SUMMARY:BEGIN -->", "<!-- SUMMARY:END -->"

REFS = [("F' full 6.92B finetune", 0.810600, None, "250M", "baseline"),
        ("CE-adapted, full residency", 0.814700, 0.5888, "250M", "baseline")]


def downstream_means():
    if not os.path.exists(DS):
        return {}
    lines = [l for l in open(DS) if not l.lstrip().lstrip('"').startswith("#")]
    acc = {}
    for r in csv.DictReader(lines):
        if r.get("metric") == "acc":
            acc.setdefault(r["cell"], []).append(float(r["cell_acc"]))
    return {k: sum(v) / len(v) for k, v in acc.items()}


def cells():
    ds, out = downstream_means(), []
    for p in glob.glob(os.path.join(DATA_DIR, "ple_*.json")):
        if os.path.basename(p).startswith(("ple_parity", "ple_heldout", "ple_calib")):
            continue
        try:
            r = json.load(open(p))
        except Exception:
            continue
        if "final_bpb" not in r or str(r.get("rank")) != "off":
            continue
        fs = r.get("free_set") or ",".join(str(i) for i in range(r.get("free_layers", 0)))
        if not fs:
            continue
        n = len([x for x in fs.split(",") if x.strip()])
        out.append({"tag": r["tag"], "fs": fs, "slots": (16 - n) * 8 + n * 64,
                    "tok": r["train_tokens"], "attn": r.get("lora_attn", 0),
                    "seed": r.get("data_seed", 0), "bpb": r["final_bpb"],
                    "acc": ds.get(r["tag"])})
    return sorted(out, key=lambda c: c["bpb"])


def table():
    rows = ["| cell | free set | memory | tokens | attn | seed | BPB | recovery | mean acc |",
            "|---|---|---|---|---|---|---|---|---|"]
    for c in cells():
        rec = (1 - (c["bpb"] - BASE) / (IMPOSE - BASE)) * 100
        acc = f"{c['acc']:.4f}" if c["acc"] is not None else "—"
        rows.append(f"| `{c['tag']}` | {c['fs']} | +{c['slots'] / 128 * 100 - 100:.1f}% | "
                    f"{c['tok'] // 10**6}M | {c['attn'] or '—'} | {c['seed']} | "
                    f"{c['bpb']:.6f} | {rec:.2f}% | {acc} |")
    for nm, b, a, tok, mem in REFS:
        rec = (1 - (b - BASE) / (IMPOSE - BASE)) * 100
        rows.append(f"| *{nm}* | — | *{mem}* | *{tok}* | — | — | *{b:.6f}* | *{rec:.2f}%* | "
                    f"{f'*{a:.4f}*' if a else '—'} |")
    return "\n".join(rows)


def main():
    n_scored = sum(1 for c in cells() if c["acc"] is not None)
    stamp = (f"*Generated by `analysis/ple/summary_table.py` from the per-cell JSONs and "
             f"`layer_freeing_downstream.csv`. Do not edit by hand — run the script. "
             f"{len(cells())} cells, {n_scored} scored downstream.*\n\n"
             f"BPB lower is better; recovery is the share of the constraint's BPB damage undone "
             f"(0% = residency imposed untrained at 2.7507, 100% = base model with free routing at "
             f"0.6727). Mean acc is over ten 0-shot tasks, higher better (base free routing 0.6823, "
             f"imposed untrained 0.3164); `—` means not scored. Memory is extra resident expert "
             f"slots against full residency. `attn` is the LoRA rank on the attention projections.")
    block = f"{BEGIN}\n\n{stamp}\n\n{table()}\n\n{END}"
    if "--write" in sys.argv:
        s = open(DOC).read()
        if BEGIN not in s or END not in s:
            sys.exit(f"markers not found in {os.path.basename(DOC)}; add {BEGIN} / {END} first")
        pre, rest = s.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        open(DOC, "w").write(pre + block + post)
        print(f"[write] {len(cells())} cells ({n_scored} scored) -> {os.path.basename(DOC)}")
    else:
        print(block)


if __name__ == "__main__":
    main()
